GET localhost:8080/auth/uuid

###
POST localhost:8080/auth/token
Content-Type: application/json

{
  "uuid": ""
}

###
GET localhost:8080/auth/token/update
Authorization: Bearer

###
GET localhost:8080/catalog/all?filterBy=upward&limit=4&offset=1
Authorization: Bearer

###
GET localhost:8080/item/5
Authorization: Bearer

###
GET localhost:8080/catalog/bracelet
Authorization: Bearer
